# Generated by Django 6.0.1 on 2026-03-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_variation_size_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size_variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Color_Variation',
        ),
        migrations.DeleteModel(
            name='Size_Variation',
        ),
    ]
