# Generated by Django 6.0.1 on 2026-03-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_products_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='variation',
        ),
    ]
