# Generated by Django 6.0.1 on 2026-03-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_products_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
