# Generated by Django 6.0.1 on 2026-03-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='store.products'),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('products', 'size', 'color')},
        ),
    ]
