# Generated by Django 6.0.1 on 2026-03-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_variation'),
        ('store', '0007_alter_variation_options_alter_variation_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
