# Generated by Django 6.0.1 on 2026-03-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.AlterField(
            model_name='variations',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.products'),
        ),
        migrations.AlterField(
            model_name='variations',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variations',
            unique_together={('product', 'size', 'color')},
        ),
    ]
